# Imagem de Origem
FROM node:18-alpine
# Diretório de trabalho(é onde a aplicação ficará dentro do container).
WORKDIR /app
# Adicionando `/app/node_modules/.bin` para o $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Instalando dependências da aplicação e armazenando em cache.
COPY . .
RUN npm install -g npm@9.6.7
RUN npm install 
# Inicializa a aplicação
CMD [ "npm", "start" ]